
package com.calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorImpl", targetNamespace = "http://calculator.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorImpl {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addReturn", targetNamespace = "http://calculator.com")
    @RequestWrapper(localName = "add", targetNamespace = "http://calculator.com", className = "com.calculator.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://calculator.com", className = "com.calculator.AddResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "http://calculator.com")
        int a,
        @WebParam(name = "b", targetNamespace = "http://calculator.com")
        int b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "divideReturn", targetNamespace = "http://calculator.com")
    @RequestWrapper(localName = "divide", targetNamespace = "http://calculator.com", className = "com.calculator.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://calculator.com", className = "com.calculator.DivideResponse")
    public int divide(
        @WebParam(name = "a", targetNamespace = "http://calculator.com")
        int a,
        @WebParam(name = "b", targetNamespace = "http://calculator.com")
        int b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "multiplyReturn", targetNamespace = "http://calculator.com")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://calculator.com", className = "com.calculator.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://calculator.com", className = "com.calculator.MultiplyResponse")
    public int multiply(
        @WebParam(name = "a", targetNamespace = "http://calculator.com")
        int a,
        @WebParam(name = "b", targetNamespace = "http://calculator.com")
        int b);

    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "substractReturn", targetNamespace = "http://calculator.com")
    @RequestWrapper(localName = "substract", targetNamespace = "http://calculator.com", className = "com.calculator.Substract")
    @ResponseWrapper(localName = "substractResponse", targetNamespace = "http://calculator.com", className = "com.calculator.SubstractResponse")
    public int substract(
        @WebParam(name = "a", targetNamespace = "http://calculator.com")
        int a,
        @WebParam(name = "b", targetNamespace = "http://calculator.com")
        int b);

}
